### ISSUE TITLE
Récupération des données sur fibre

### ISSUE THREAD

**Issue by BabC** [jeanfabrice/livebox-collect#1]
Salut,

Ton code me renvoie que des objets vides pour getMIBs :
`{ status: { dsl: {} } }`
Idem pour getDSLStats
`{ status:
   { ReceiveBlocks: 0,
     TransmitBlocks: 0,
     CellDelin: 0,
     LinkRetrain: 0,
     InitErrors: 0,
     InitTimeouts: 429496729
     LossOfFraming: 0,
     ErroredSecs: 0,
     SeverelyErroredSecs: 0,
     FECErrors: 0,
     ATUCFECErrors: 0,
     HECErrors: 0,
     ATUCHECErrors: 0,
     CRCErrors: 0,
     ATUCCRCErrors: 0 } }`

Mais les autres fonctions de "base" marchent bien (deviceInfo).

Y a-t-il des chances pour que cela vienne du fait que je sois sous fibre ? Une idée des chemin d'accès aux même méthode dans ce cas là ?

**Comment by jeanfabrice** [comment]
Je pense que cela vient du fait que la fibre, ce n'est pas de l'ADSL justement. Et comme les valeurs relevées par GetDSLstats sont liées à des métriques ADSL, il est certainement normal que celles ci soient nulles ou inconsistantes.

Quand à ```getMibs()```, il faudrait trouver le nom de la MIB associée à la fibre. Car là encore, la MIB 'dsl' ne doit pas être la bonne. Sur ce point, le mieux est d'observer les requêtes Ajax faites par ton navigateur sur l'interface web de la livebox, et rechercher celle qui contient des données similaires à celles-ci, envoyées en POST sur le endpoint http://livebox.home/ws (sachant que dans ton cas, la valeur de l'attribut 'mibs' sera différente) :
```json
{"service":"NeMo.Intf.data","method":"getMIBs","parameters":{"mibs":"dsl"}}
```
